In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv("dataset.csv")

In [3]:
movies.head(10)

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,109.720,8.7,17355
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,92.048,8.7,23144
2,315162,Puss in Boots: The Last Wish,Puss in Boots discovers that his passion for a...,2022-12-07,6689.647,8.6,2504
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,57.998,8.6,10503
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,55.299,8.6,13687
5,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-19,27.945,8.6,4030
6,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2002-09-20,76.270,8.5,13851
7,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,42.266,8.5,6979
8,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,95.479,8.5,9431
9,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,80.513,8.5,15123

In [4]:
movies.describe()

                 id    popularity  vote_average    vote_count
count  1.000000e+04  10000.000000  10000.000000  10000.000000
mean   1.717954e+05     24.737967      6.705490   1613.442000
std    2.254123e+05    109.157223      0.687104   2762.985388
min    2.000000e+00      0.600000      5.400000    200.000000
25%    1.017750e+04      9.455500      6.200000    320.000000
50%    3.260650e+04     13.413000      6.700000    605.000000
75%    3.328988e+05     22.195000      7.200000   1533.250000
max    1.024530e+06   6689.647000      8.700000  33043.000000

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10000 non-null  int64
 1   title         10000 non-null  object
 2   overview      9998 non-null   object
 3   release_date  10000 non-null  object
 4   popularity    10000 non-null  float64
 5   vote_average  10000 non-null  float64
 6   vote_count    10000 non-null  int64
dtypes: float64(2), int64(2), object(3)
memory usage: 547.0+ KB

In [6]:
movies.isnull().sum()

id              0
title           0
overview        2
release_date    0
popularity      0
vote_average    0
vote_count      0
dtype: int64

In [7]:
movies.columns

Index(['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average',
       'vote_count'],
      dtype='object')

In [8]:
movies= movies[['id','title','overview']]

In [9]:
movies

,id,title,overview
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
2,315162,Puss in Boots: The Last Wish,Puss in Boots discovers that his passion for a...
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...
4,424,Schindler's List,The true story of how businessman Oskar Schind...
...,...,...,...
9995,64586,Sleeping Beauty,"A haunting erotic fairytale about Lucy, a youn..."
9996,9278,Freejack,Time-traveling bounty hunters find a doomed ra...
9997,178809,The Colony,"Forced underground by the next ice age, a stru..."
9998,49950,The Roommate,"When Sara, a young design student from Iowa, a..."
9999,10992,Cats & Dogs,When a professor develops a vaccine that elimi...

In [10]:
movies['tags'] = movies['overview']

In [11]:
movies

,id,title,overview,tags
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,Framed in the 1940s for the double murder of h...
2,315162,Puss in Boots: The Last Wish,Puss in Boots discovers that his passion for a...,Puss in Boots discovers that his passion for a...
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...
4,424,Schindler's List,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...
...,...,...,...,...
9995,64586,Sleeping Beauty,"A haunting erotic fairytale about Lucy, a youn...","A haunting erotic fairytale about Lucy, a youn..."
9996,9278,Freejack,Time-traveling bounty hunters find a doomed ra...,Time-traveling bounty hunters find a doomed ra...
9997,178809,The Colony,"Forced underground by the next ice age, a stru...","Forced underground by the next ice age, a stru..."
9998,49950,The Roommate,"When Sara, a young design student from Iowa, a...","When Sara, a young design student from Iowa, a..."
9999,10992,Cats & Dogs,When a professor develops a vaccine that elimi...,When a professor develops a vaccine that elimi...

In [13]:
new_data = movies.drop(columns=['overview']).iloc[~movies.index.isin(range(1000, 10001))]

In [14]:
new_data

,id,title,tags
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
2,315162,Puss in Boots: The Last Wish,Puss in Boots discovers that his passion for a...
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...
4,424,Schindler's List,The true story of how businessman Oskar Schind...
...,...,...,...
995,54186,Confessions,A psychological thriller of a grieving mother ...
996,13386,I'm Starting from Three,"Gaetano, giovane napoletano, decide di lasciar..."
997,644089,Blue Bayou,As a Korean-American man raised in the Louisia...
998,31216,I Can't Think Straight,I CAN'T THINK STRAIGHT is a 2007 romance movie...
999,1726,Iron Man,"After being held captive in an Afghan cave, bi..."

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv= CountVectorizer(max_features=100, stop_words='english')

In [17]:
cv

CountVectorizer(max_features=100, stop_words='english')

In [18]:
vector= cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [19]:
vector.shape

(1000, 100)

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
similarity=cosine_similarity(vector)

In [22]:
similarity

array([[1.        , 0.08703883, 0.10206207, ..., 0.40824829, 0.        ,
        0.        ],
       [0.08703883, 1.        , 0.10660036, ..., 0.10660036, 0.        ,
        0.        ],
       [0.10206207, 0.10660036, 1.        , ..., 0.25      , 0.        ,
        0.        ],
       ...,
       [0.40824829, 0.10660036, 0.25      , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [23]:
new_data[new_data['title']=="The Godfather"].index[0]

0

In [24]:
distance=sorted(list(enumerate(similarity[0])), reverse =True , key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather Part II
Joker
The Mitchells vs. the Machines
The Batman

In [25]:
def recommend(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse= True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [26]:
recommend('Iron Man')

Snatch
Train to Busan
Iron Man
Mortal Kombat Legends: Battle of the Realms
Monty Python and the Holy Grail

In [27]:
import pickle

In [28]:
pickle.dump(new_data, open('movies_list.pkl','wb'))

In [29]:
pickle.dump(similarity, open('similarity.pkl','wb'))

In [30]:
pickle.load(open('movies_list.pkl','rb'))

,id,title,tags
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
2,315162,Puss in Boots: The Last Wish,Puss in Boots discovers that his passion for a...
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...
4,424,Schindler's List,The true story of how businessman Oskar Schind...
...,...,...,...
995,54186,Confessions,A psychological thriller of a grieving mother ...
996,13386,I'm Starting from Three,"Gaetano, giovane napoletano, decide di lasciar..."
997,644089,Blue Bayou,As a Korean-American man raised in the Louisia...
998,31216,I Can't Think Straight,I CAN'T THINK STRAIGHT is a 2007 romance movie...
999,1726,Iron Man,"After being held captive in an Afghan cave, bi..."

In [31]:
pickle.load(open('similarity.pkl','rb'))

array([[1.        , 0.08703883, 0.10206207, ..., 0.40824829, 0.        ,
        0.        ],
       [0.08703883, 1.        , 0.10660036, ..., 0.10660036, 0.        ,
        0.        ],
       [0.10206207, 0.10660036, 1.        , ..., 0.25      , 0.        ,
        0.        ],
       ...,
       [0.40824829, 0.10660036, 0.25      , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])